### PR TITLE
Use compiler's inputFileSystem for reading the source files and sourcemaps.

### LINKED ISSUE #2: This uses node fs directly to read JS and sourcemap files
... instead of the compiler's inputFileSystem. As a result if the files don't actually exist on disk, this doesn't work.

### PR DESCRIPTION
**Pull request by Arnavion**
Fixes #2

### CODE REVIEW

**Comment by sokra** [comment]
Yeah... I see what you want to do...

But `_compiler` is a private API, so we better expose the inputFileSystem as `this.fs` to loaders. Would you like to do a PR there. This affects more loaders as many of them use `require("fs")`. `this.fs` could automatically track dependencies too...

**Comment by Arnavion** [comment]
That makes sense. I'll do that.

**Comment by fzaninotto** [comment]
It doesn't seem to be enough. Although a webpack build on fs works, with your patch a webpack-dev-server fails with the following error:

```
		callbacks[i].apply(null, args);
		             ^
TypeError: undefined is not a function
    at Storage.finished (path/to/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at evalmachine.<anonymous>:334:14
    at path/to/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:102:5
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

**Comment by Arnavion** [comment]
@fzaninotto Sorry, I don't use webpack any more so I'm not going to push for this. Maybe try seeing what exactly `callback[i]` is (presumably not a function) and how it came to be there.

**Comment by Strate** [comment]
What's here? Why just not to merge it?

**Comment by jedwards1211** [comment]
@sokra if `_compiler` is private API for loaders but not for plugins, perhaps this should be some sort of plugin/loader hybrid instead?

**Comment by Arnavion** [comment]
I'm not using webpack any more and have no idea if this PR is still valid or not, so I'm closing it. If someone else needs it please feel free to submit your own PR.

**Pull request closed without merging**
